version: "3.9"

services:
  mongo:
    image: mongo:6
    container_name: mongo_container
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend # path where your backend Dockerfile is located
    container_name: backend_container
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://admin:admin123@mongo:27017/todo_db?authSource=admin
      MONGO_DB: todo_db
      MONGO_COLLECTION: tasks

  frontend:
    image: nginx:alpine
    container_name: frontend_container
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    depends_on:
      - backend

volumes:
  mongo_data:
